### ISSUE TITLE
Rewrite in C#

### ISSUE THREAD

**Issue by gillianmilne** [GlobalX/pockybot#110]
Something @Evangelinexx was talking about yesterday. Might be worth discussing pros and cons of this. Bit pie in the sky but could be worth `¯\_(ツ)_/¯ `?

**Comment by jimcullenaus** [comment]
Pro: It's an opportunity to clean up the way everything is done, paying back some technical debt.
Pro: Debugging locally will probably be possible?
Con: Are there good Webex libraries available? I thought one reason we went with JS in the first place was due to the `ciscospark` npm package. Would rather not have to deal with interacting with their API directly.
Con: A large amount of development time spent *not* adding new features or fixing existing known bugs.

**Comment by jimcullenaus** [comment]
Point for discussion: It would perhaps not need to be done all at once. We could switch over triggers from the JS version to the C# version one at a time, though we would have to plan our design carefully ahead to avoid getting in to the same pasta-like code we currently have.

**Comment by jimcullenaus** [comment]
* **Con**: C# style guides are absolutely shite

**Comment by jonyeezs** [comment]
**Pro**: Nothing wrong with Typescript :smile: 

_P.S: hi!_

**Comment by Lauraducky** [comment]
In progress [here](https://github.com/GlobalX/PockyBot.NET)
